[package]
name = "cz"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "check-zip"
path = "src/main.rs"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.54", features = ["derive"] }
colour = "2.1.0"
zip = "2.2"

[dev-dependencies]
tempfile = "3.13"

